### ISSUE TITLE
Arquivos-objeto no repositório

### ISSUE THREAD

**Issue by vinipsmaker** [jleandrof/Jacks-Useless-Talents#1]
Tem alguns arquivos-objeto, tipo o DoublyLinkedList.o e todos os arquivos que terminam em ".o", no repositório. Esse é o tipo de arquivo que você não precisa distribuir e é dependente da arquitetura/plataforma.

Você devia "desversionar" (git rm ...; git commit; git push) esses arquivos.

**Comment by vinipsmaker** [comment]
Já fechou a issue?

![](https://psychomantys.files.wordpress.com/2013/03/renasce2qitkk4.jpg)

**Comment by jleandrof** [comment]
Tinha esquecido. Pelo menos te deu motivo pra usar essa carta.
